title = "Red Hat | Public Sector"
baseURL = "https://redhatgov.io/"
theme = "pf4-redhat"
languageCode = "en-us"
metaDataFormat = "yaml"

[markup]
    defaultMarkdownHandler = "blackfriday"

[params]
    description = "Tried. Tested. Trusted."
    #jigBackend = "http://localhost:8000"
    jigBackend = "https://jig.polyglot.academy"

[taxonomies]
    workshop = "workshops"

[blackfriday]
    smartypants = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Workshops"
    identifier = "workshops"
    weight = 100

[[menu.main]]
    name = "Events"
    identifier = "events"
    weight = 30
    url = "https://www.redhat.com/en/events"
